name: kdllm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.10
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - appnope==0.1.4
      - asttokens==2.4.1
      - attrs==24.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.1
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.8
      - decorator==5.1.1
      - distro==1.9.0
      - executing==2.1.0
      - fastjsonschema==2.21.0
      - fonttools==4.54.1
      - h11==0.14.0
      - h5py==3.12.1
      - holidays==0.64
      - httpcore==1.0.6
      - httpx==0.27.2
      - idna==3.10
      - ipykernel==6.29.5
      - ipython==8.29.0
      - ipywidgets==8.1.5
      - jedi==0.19.1
      - jiter==0.7.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kaleido==0.2.1
      - kiwisolver==1.4.7
      - matplotlib==3.9.3
      - matplotlib-inline==0.1.7
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numpy==2.1.3
      - openai==1.54.3
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - prompt-toolkit==3.0.48
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pvlib==0.11.2
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.32.3
      - rpds-py==0.21.0
      - scipy==1.15.1
      - six==1.16.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - tenacity==9.0.0
      - tornado==6.4.1
      - tqdm==4.67.0
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.13
